# -*- coding: utf-8 -*-
"""Build data.js for the Making Time 2026 page.
Lineup + official artist links: https://makingtimeisrad.com/lineup/
(RA listing: https://ra.co/events/2395557)
"""
import json, os

GROUPMAP = {'T': 'techno', 'E': 'electro', 'J': 'jungle', 'H': 'house', 'A': 'ambient', 'M': 'folk', 'B': 'bands'}

LINEUP = [
"1morning",
"@",
"afro.fem",
"Alex Zhang Hungtai",
"Andrew Max FT",
"Arthur (DE)",
"Aurora Halal",
"Autumns",
"Avalon Emerson",
"Baalti",
"BASHKKA",
"Batu",
"Beautiful Swimmers",
"Bianca Lexis",
"Bicep",
"Binh",
"Bobby Beethoven",
"Cancer House",
"Carla dal Forno",
"Carlos Souffront",
"Carrier",
"Cashu",
"CCL",
"Chee Shimizu",
"Ciro Vitiello",
"Colombian Drone Mafia",
"Crespi Drum Syndicate",
"Cry",
"Cubby",
"Dagmar Zuniga",
"Dania",
"Daniel Avery",
"Daphni",
"De Schuurman",
"Debit",
"Deep Creep",
"DJ Godfather",
"DJ LAG",
"DJ MARIA.",
"DJ Masda",
"DJ Papaya",
"DJ Python",
"DJ Sundae",
"DJ SWISHA",
"Dopplereffekt",
"ear",
"Eev Frances",
"Ehua",
"Elori Saxl & Henry Solomon",
"Emily A. Sprague",
"Eris Drew",
"Erol Alkan",
"Father Dionysios Tabakis",
"Gabber Eleganza",
"Gavsborg",
"Gravers Lane",
"Hervé",
"Honcho",
"Ian Kim Judd",
"Identified Patient",
"Introspekt",
"Ivan Liechti",
"JASSS",
"Jeff Parker",
"Jeff Zeigler",
"JEWELSSEA",
"JJJJJerome Ellis",
"John Talabot",
"Joy Guidry",
"Jump Source",
"Kiernan Laveaux",
"Kim Gordon",
"Konduku",
"LEECH",
"Lena Willikens",
"Loidis",
"Loradeniz",
"Los Thuthanaka",
"Luke Mele",
"Ma Sha",
"Maara",
"mad miran",
"Main Phase",
"Marcel Dettmann",
"Mario Cotto",
"Mark Ernestus",
"Martyn",
"Mary Lattimore",
"Matt Werth",
"Mike Midnight",
"Mississippi Records",
"Moopie",
"Naone",
"Nashpaints",
"Nídia",
"Octo Octa",
"OKO DJ",
"oma totem",
"Optimo (Espacio)",
"Pan·American",
"Paperclip Minimiser",
"Paula Tape",
"Pavel Milyakov",
"Pender Street Steppers",
"Phil Yeah",
"Pilooski",
"Qoso",
"QRTR",
"Quiet Light",
"RHR",
"Richard",
"Robert Aiki Aubrey Lowe",
"Roza Terenzi",
"Russell Alexander",
"Sandwell District",
"Security Dog",
"Sergeant",
"SEXTILE",
"Shai FM",
"Shane Parish",
"Shaun D",
"Skee Mask",
"Soul Summit",
"Space Drum Meditation",
"Special Guest DJ",
"Spivak",
"Spray",
"Stone",
"The Space Lady",
"Theo Parrish",
"They Are Gutting A Body Of Water",
"Tiga",
"Topdown Dialectic",
"Tornado Wallace",
"Trickpony",
"Unai Trotti",
"Universal Cave",
"upsammy",
"Valentina Magaletti",
"Verraco",
"Vlada",
"Vladimir Ivkovic",
"Wata Igarashi",
"Westov Temple",
"x3butterfly",
"Yu Su",
"Yumi",
"Zillas on Acid"
]

META = {
"1morning": ["Los Angeles", "US", "T", ["techno", "90s-informed", "vinyl sets"], None],
"@": ["Philadelphia", "US", "M", ["folk", "ambient pop"], None],
"afro.fem": ["", None, "", [], None],
"Alex Zhang Hungtai": ["Taipei / Lisbon", "TW", "M", ["saxophone", "improvised"], "alexzhanghungtai"],
"Andrew Max FT": ["", None, "", [], None],
"Arthur (DE)": ["Berlin", "DE", "T", ["leftfield"], "arthur-de"],
"Aurora Halal": ["New York", "US", "T", ["techno", "trance"], "aurorahalal"],
"Autumns": ["Derry", "IE", "T", ["EBM", "post-punk"], "autumns"],
"Avalon Emerson": ["Berlin / San Francisco", "DE", "TH", ["techno", "indie-electronic", "pop"], "avalonemerson"],
"Baalti": ["San Francisco", "US", "H", ["south asian house"], "baalti"],
"BASHKKA": ["Munich", "TR", "T", ["club", "techno"], "bashkka"],
"Batu": ["Bristol", "GB", "T", ["UK bass", "techno"], "batu-uk"],
"Beautiful Swimmers": ["Washington DC", "US", "H", ["house", "disco"], "beautifulswimmers"],
"Bianca Lexis": ["New York", "US", "H", ["disco", "club"], "biancalexis"],
"Bicep": ["Belfast / London", "GB", "TJ", ["breaks", "electronica", "techno"], "bicep"],
"Binh": ["Berlin", "DE", "T", ["minimal"], "binh"],
"Bobby Beethoven": ["", None, "", [], None],
"Cancer House": ["", None, "", [], None],
"Carla dal Forno": ["Melbourne / London", "AU", "B", ["post-punk", "minimal pop"], "carladalforno"],
"Carlos Souffront": ["Ann Arbor", "US", "TE", ["acid", "electro", "techno"], "carlossouffront"],
"Carrier": ["London", "GB", "T", ["dub techno", "bass"], "carrier"],
"Cashu": ["São Paulo", "BR", "T", ["latin techno", "club"], "cashu"],
"CCL": ["Berlin / Seattle", "US", "T", ["bass", "leftfield club"], "ccl"],
"Chee Shimizu": ["Tokyo", "JP", "A", ["obscure", "balearic"], "cheeshimizu"],
"Ciro Vitiello": ["Philadelphia", "US", "T", ["techno"], None],
"Colombian Drone Mafia": ["Bogotá", "CO", "M", ["drone"], None],
"Crespi Drum Syndicate": ["New York", "US", "B", ["percussion ensemble"], None],
"Cry": ["New York", "US", "B", ["band"], None],
"Cubby": ["New York", "US", "H", ["disco"], None],
"Dagmar Zuniga": ["", None, "M", ["vocal", "folk", "ambient"], None],
"Dania": ["Barcelona", "ES", "M", ["ambient", "vocal"], None],
"Daniel Avery": ["London", "GB", "T", ["techno", "ambient"], "danielavery"],
"Daphni": ["London", "CA", "H", ["house", "Caribou"], "daphni"],
"De Schuurman": ["The Hague", "NL", "T", ["bubbling"], "deschuurman"],
"Debit": ["New York", "MX", "A", ["experimental", "mayan flutes"], "debit"],
"Deep Creep": ["New York", "US", "T", ["club"], None],
"DJ Godfather": ["Detroit", "US", "E", ["ghettotech", "electro"], "djgodfather"],
"DJ LAG": ["Durban", "ZA", "T", ["gqom"], "djlag"],
"DJ MARIA.": ["Tokyo", "JP", "T", ["techno", "bass"], "djmaria"],
"DJ Masda": ["Tokyo / Berlin", "JP", "T", ["minimal"], "djmasda"],
"DJ Papaya": ["Philadelphia", "US", "H", ["club", "eclectic"], "djpapaya"],
"DJ Python": ["New York", "US", "AH", ["deep reggaeton", "ambient club"], "djpython"],
"DJ Sundae": ["Paris", "FR", "H", ["balearic", "chill-out"], "djsundae"],
"DJ SWISHA": ["New York", "US", "T", ["club", "jersey"], "djswisha"],
"Dopplereffekt": ["Detroit", "US", "E", ["electro", "live"], "dopplereffekt"],
"ear": ["", None, "B", ["indie"], None],
"Eev Frances": ["Philadelphia", "US", "H", ["eclectic"], None],
"Ehua": ["London", "IT", "T", ["bass", "club"], "ehua"],
"Elori Saxl & Henry Solomon": ["New York", "US", "M", ["ambient classical", "saxophone"], None],
"Emily A. Sprague": ["Los Angeles", "US", "M", ["modular", "ambient"], None],
"Eris Drew": ["New Hampshire", "US", "H", ["house", "rave"], "erisdrew"],
"Erol Alkan": ["London", "GB", "T", ["electro", "indie dance"], "erolalkan"],
"Father Dionysios Tabakis": ["", "GR", "M", ["byzantine chant"], None],
"Gabber Eleganza": ["Milan", "IT", "T", ["gabber", "hakken"], "gabbereleganza"],
"Gavsborg": ["Kingston", "JM", "T", ["dancehall experimental", "Equiknoxx"], "gavsborg"],
"Gravers Lane": ["Philadelphia", "US", "T", ["club"], None],
"Hervé": ["London", "GB", "H", ["bass house"], "herve"],
"Honcho": ["Pittsburgh", "US", "H", ["house", "queer party"], None],
"Ian Kim Judd": ["New York", "US", "T", ["club"], None],
"Identified Patient": ["Amsterdam", "NL", "TE", ["EBM", "techno"], "identifiedpatient"],
"Introspekt": ["Los Angeles", "US", "H", ["UKG"], "introspekt"],
"Ivan Liechti": ["Geneva", "CH", "A", ["leftfield"], None],
"JASSS": ["Berlin", "ES", "T", ["techno", "experimental"], "jasss"],
"Jeff Parker": ["Los Angeles", "US", "M", ["jazz guitar"], None],
"Jeff Zeigler": ["Philadelphia", "US", "B", ["ambient", "shoegaze"], "zeigler"],
"JEWELSSEA": ["Philadelphia", "US", "T", ["club", "live"], "jewelssea"],
"JJJJJerome Ellis": ["Virginia Beach", "US", "M", ["stutter music", "poetry"], None],
"John Talabot": ["Barcelona", "ES", "H", ["house", "disco", "balearic"], "johntalabot"],
"Joy Guidry": ["New York", "US", "M", ["bassoon", "free jazz"], None],
"Jump Source": ["New York", "US", "H", ["dream house live"], "jumpsource"],
"Kiernan Laveaux": ["Cleveland", "US", "T", ["techno", "wave"], "kiernanlaveaux"],
"Kim Gordon": ["Los Angeles", "US", "B", ["Sonic Youth", "noise rock"], None],
"Konduku": ["Amsterdam", "TR", "T", ["percussive techno"], "konduku"],
"LEECH": ["New York", "US", "T", ["club"], None],
"Lena Willikens": ["Düsseldorf", "DE", "T", ["leftfield", "EBM"], "lenawillikens"],
"Loidis": ["Kansas City / New York", "US", "A", ["ambient", "deep techno", "dub house"], "loidis"],
"Loradeniz": ["Amsterdam", "TR", "M", ["ambient", "vocal", "live"], "loradeniz"],
"Los Thuthanaka": ["New York", "BO", "M", ["andean experimental"], None],
"Luke Mele": ["Philadelphia", "US", "T", ["club"], "lukemele"],
"Ma Sha": ["New York", "RU", "T", ["bass", "club"], "masha-ny"],
"Maara": ["Montréal", "CA", "T", ["trance", "club"], "maara"],
"mad miran": ["Amsterdam", "NL", "T", ["jungle", "eclectic"], "madmiran"],
"Main Phase": ["Copenhagen", "DK", "H", ["UKG"], "mainphase"],
"Marcel Dettmann": ["Berlin", "DE", "T", ["berghain techno"], "marceldettmann"],
"Mario Cotto": ["Los Angeles", "US", "H", ["eclectic", "KCRW"], "mariocotto"],
"Mark Ernestus": ["Berlin", "DE", "T", ["dub techno", "Basic Channel"], "markernestus"],
"Martyn": ["Washington DC", "NL", "TJ", ["dubstep", "techno"], "martyn"],
"Mary Lattimore": ["Los Angeles", "US", "M", ["harp", "ambient", "folk"], None],
"Matt Werth": ["New York", "US", "A", ["eclectic"], None],
"Mike Midnight": ["Philadelphia", "US", "H", ["house"], None],
"Mississippi Records": ["Portland", "US", "A", ["archival", "folk"], None],
"Moopie": ["Melbourne", "AU", "T", ["ambient club", "A Colourful Storm"], "moopie-au"],
"Naone": ["Melbourne", "AU", "T", ["techno"], "naone"],
"Nashpaints": ["", None, "", [], None],
"Nídia": ["Lisbon", "PT", "T", ["batida", "Príncipe"], "nidia"],
"Octo Octa": ["New Hampshire", "US", "H", ["house", "rave"], "octoocta"],
"OKO DJ": ["Marseille", "FR", "T", ["leftfield", "trance"], "okodj"],
"oma totem": ["Philadelphia", "US", "A", ["ambient"], None],
"Optimo (Espacio)": ["Glasgow", "GB", "T", ["eclectic", "post-punk club"], "optimo"],
"Pan·American": ["Chicago", "US", "M", ["ambient dub", "slide guitar"], None],
"Paperclip Minimiser": ["", None, "", [], None],
"Paula Tape": ["Milan", "CL", "H", ["house", "balearic"], "Paulatape"],
"Pavel Milyakov": ["Moscow / Berlin", "RU", "A", ["buttechno", "experimental"], "buttechno"],
"Pender Street Steppers": ["Vancouver", "CA", "H", ["house", "Mood Hut"], "penderstreetsteppers"],
"Phil Yeah": ["Philadelphia", "US", "H", ["house"], None],
"Pilooski": ["Paris", "FR", "H", ["disco edits"], "pilooski"],
"Qoso": ["Baltimore", "US", "T", ["club"], "qoso"],
"QRTR": ["New York", "US", "T", ["club", "ambient rave"], "qrtr"],
"Quiet Light": ["", None, "", [], None],
"RHR": ["New York", "US", "H", ["house"], None],
"Richard": ["", None, "", [], None],
"Robert Aiki Aubrey Lowe": ["New York", "US", "M", ["modular", "vocal drone"], None],
"Roza Terenzi": ["Berlin", "AU", "T", ["breaks", "tech-trance"], "rozaterenzi"],
"Russell Alexander": ["Philadelphia", "US", "A", ["ambient", "eclectic"], None],
"Sandwell District": ["Berlin / UK", "GB", "T", ["techno", "industrial"], "sandwelldistrict"],
"Security Dog": ["Philadelphia", "US", "T", ["club"], "securitydog"],
"Sergeant": ["", None, "A", ["leftfield"], None],
"SEXTILE": ["Los Angeles", "US", "B", ["synth-punk live"], "sextile"],
"Shai FM": ["Philadelphia", "US", "H", ["house"], "shaifm"],
"Shane Parish": ["Asheville", "US", "M", ["guitar"], None],
"Shaun D": ["The Hague", "NL", "J", ["bubbling"], None],
"Skee Mask": ["Munich", "DE", "TA", ["breaks", "IDM techno"], "skeemask"],
"Soul Summit": ["New York", "US", "H", ["house", "block party"], None],
"Space Drum Meditation": ["Berlin", "DE", "T", ["tribal techno"], "spacedrummeditation"],
"Special Guest DJ": ["New York", "US", "T", ["club", "mystery"], "specialguestdj"],
"Spivak": ["", None, "", [], None],
"Spray": ["Manchester", "GB", "H", ["UKG", "bass"], "spray"],
"Stone": ["", None, "AT", ["ambient techno", "microhouse", "dub techno"], None],
"The Space Lady": ["Colorado", "US", "M", ["outsider synth pop", "vocal"], None],
"Theo Parrish": ["Detroit", "US", "H", ["detroit house", "jazz"], "theoparrish"],
"They Are Gutting A Body Of Water": ["Philadelphia", "US", "B", ["shoegaze"], None],
"Tiga": ["Montréal", "CA", "TE", ["electroclash", "techno"], "tiga"],
"Topdown Dialectic": ["", None, "A", ["ambient dub techno"], None],
"Tornado Wallace": ["Melbourne / Berlin", "AU", "H", ["balearic house"], "tornadowallace"],
"Trickpony": ["Montréal", "CA", "H", ["trance-house"], None],
"Unai Trotti": ["London", "ES", "T", ["minimal"], "unaitrotti"],
"Universal Cave": ["Philadelphia", "US", "H", ["disco", "psychedelic"], "universalcave"],
"upsammy": ["Amsterdam", "NL", "TA", ["IDM techno", "leftfield"], "upsammy"],
"Valentina Magaletti": ["London", "IT", "M", ["percussion", "experimental"], "valentinamagaletti"],
"Verraco": ["Medellín", "CO", "T", ["latin techno", "bass"], "verraco"],
"Vlada": ["New York", "UA", "T", ["techno", "trance"], "vlada"],
"Vladimir Ivkovic": ["Düsseldorf", "RS", "T", ["leftfield", "slow techno"], "vladimirivkovic"],
"Wata Igarashi": ["Tokyo", "JP", "T", ["hypnotic techno"], "wataigarashi"],
"Westov Temple": ["Philadelphia", "US", "T", ["synth", "live"], "westovtemple"],
"x3butterfly": ["New York", "US", "T", ["club", "trance"], "x3butterfly"],
"Yu Su": ["Vancouver", "CN", "H", ["ambient house", "dub"], "yusu"],
"Yumi": ["Philadelphia", "US", "T", ["club"], None],
"Zillas on Acid": ["Philadelphia", "US", "TE", ["acid", "EBM", "synth"], "zillasonacid"],
}

LINKS = {
"1morning": ["https://soundcloud.com/1morning", 0],
"@": ["https://www.instagram.com/at.songs", 1],
"afro.fem": ["https://www.instagram.com/afro.fem", 0],
"Alex Zhang Hungtai": ["https://alexzhanghungtai.bandcamp.com/", 1],
"Andrew Max FT": ["https://thetrilogytapes.bandcamp.com/album/all-7s", 0],
"Arthur (DE)": ["https://www.instagram.com/arthur___666___/", 0],
"Aurora Halal": ["https://soundcloud.com/itsallhalal", 0],
"Autumns": ["https://www.instagram.com/autumns.dss", 1],
"Avalon Emerson": ["https://avalonemerson.bandcamp.com/album/the-charm", 0],
"Baalti": ["https://soundcloud.com/baalti", 0],
"BASHKKA": ["https://soundcloud.com/bashkka", 0],
"Batu": ["https://soundcloud.com/batuuk", 0],
"Beautiful Swimmers": ["https://soundcloud.com/beautifulswimmers", 0],
"Bianca Lexis": ["https://www.instagram.com/bianca__lexis", 0],
"Bicep": ["https://soundcloud.com/feelmybicep", 0],
"Binh": ["https://soundcloud.com/binh", 0],
"Bobby Beethoven": ["https://www.instagram.com/bobbybeethoven", 0],
"Cancer House": ["https://soundcloud.com/cancerhouse", 1],
"Carla dal Forno": ["https://soundcloud.com/carla-dal-forno", 1],
"Carlos Souffront": ["https://soundcloud.com/csouffront", 0],
"Carrier": ["https://soundcloud.com/driftingover", 1],
"Cashu": [None, 0],
"CCL": ["https://soundcloud.com/ccl-url", 0],
"Chee Shimizu": ["https://www.instagram.com/cheeshimizu", 0],
"Ciro Vitiello": ["https://www.instagram.com/ciirovitiiello", 1],
"Colombian Drone Mafia": ["https://www.instagram.com/nyksan_", 0],
"Crespi Drum Syndicate": ["https://isla.bandcamp.com/album/beats", 1],
"Cry": ["https://crynyc.bandcamp.com/album/ad-140", 1],
"Cubby": ["https://www.instagram.com/cubby.c0m", 0],
"Dagmar Zuniga": ["https://soundcloud.com/dagmarzuniga", 1],
"Dania": ["https://www.instagram.com/dania_paralaxe/", 1],
"Daniel Avery": ["https://soundcloud.com/danielavery", 1],
"Daphni": ["https://soundcloud.com/daphni", 0],
"De Schuurman": ["https://www.instagram.com/deschuurman.mp3/", 0],
"Debit": ["https://soundcloud.com/yourdebit", 1],
"Deep Creep": ["https://soundcloud.com/deep_creep", 0],
"DJ Godfather": ["https://soundcloud.com/dj-godfather", 0],
"DJ LAG": ["https://soundcloud.com/dj-lag", 0],
"DJ MARIA.": ["https://soundcloud.com/djmaria-jp", 0],
"DJ Masda": ["https://soundcloud.com/djmasda", 0],
"DJ Papaya": ["https://www.instagram.com/papaya.official", 0],
"DJ Python": ["https://soundcloud.com/worldwideunlimited", 0],
"DJ Sundae": ["https://soundcloud.com/djsundae", 0],
"DJ SWISHA": ["https://soundcloud.com/dj-swisha", 0],
"Dopplereffekt": ["https://www.instagram.com/__dopplereffekt__/", 1],
"ear": ["https://www.instagram.com/__ear_/?hl=en", 1],
"Eev Frances": ["https://www.instagram.com/eev.fr", 0],
"Ehua": ["https://soundcloud.com/ehuamusic", 0],
"Elori Saxl & Henry Solomon": ["https://elorisaxl.bandcamp.com/album/seeing-is-forgetting", 1],
"Emily A. Sprague": ["https://mlesprg.bandcamp.com/music", 1],
"Eris Drew": ["https://soundcloud.com/eris-drew", 0],
"Erol Alkan": ["https://www.instagram.com/erolalkan", 0],
"Father Dionysios Tabakis": ["https://heatcrimes.bandcamp.com/album/paradise-metal", 1],
"Gabber Eleganza": ["https://soundcloud.com/gabbereleganza", 0],
"Gavsborg": ["https://www.instagram.com/gavsborg/", 0],
"Gravers Lane": ["https://www.instagram.com/gravers_lane", 0],
"Hervé": ["https://soundcloud.com/hervespace", 0],
"Honcho": ["https://www.instagram.com/honchopgh", 0],
"Ian Kim Judd": ["https://www.instagram.com/ikjfomo", 0],
"Identified Patient": ["https://soundcloud.com/identified-patient", 0],
"Introspekt": ["https://soundcloud.com/sageintrospekt", 0],
"Ivan Liechti": ["https://soundcloud.com/mutantradio/ivan-liechti-030326-3", 0],
"JASSS": ["https://soundcloud.com/jass-29", 0],
"Jeff Parker": ["https://www.instagram.com/jeffparkersounds/", 1],
"Jeff Zeigler": ["https://www.instagram.com/jeffzeigler_", 1],
"JEWELSSEA": ["https://soundcloud.com/jewelssea", 0],
"JJJJJerome Ellis": ["https://soundcloud.com/jjjjjeromeellis", 1],
"John Talabot": ["https://soundcloud.com/john-talabot", 0],
"Joy Guidry": ["https://soundcloud.com/joyjaid", 1],
"Jump Source": ["https://jumpsource.bandcamp.com", 1],
"Kiernan Laveaux": ["https://www.instagram.com/kiernanlaveaux", 0],
"Kim Gordon": ["https://kimgordon.bandcamp.com/music", 1],
"Konduku": ["https://soundcloud.com/kondukukonduku", 0],
"LEECH": ["https://www.instagram.com/leechband/?hl=en", 0],
"Lena Willikens": ["https://soundcloud.com/lenawillikens", 0],
"Loidis": ["https://soundcloud.com/westmineral", 0],
"Loradeniz": ["https://loradeniz.bandcamp.com", 1],
"Los Thuthanaka": ["https://losthuthanaka.bandcamp.com", 1],
"Luke Mele": ["https://www.instagram.com/luke_mele", 0],
"Ma Sha": ["https://soundcloud.com/masha-ny", 0],
"Maara": ["https://soundcloud.com/maara", 0],
"mad miran": ["https://soundcloud.com/madmiran", 0],
"Main Phase": ["https://soundcloud.com/mainphase001", 0],
"Marcel Dettmann": ["https://soundcloud.com/marceldettmann", 0],
"Mario Cotto": ["https://www.instagram.com/mariocotto", 0],
"Mark Ernestus": ["https://soundcloud.com/markernestus", 0],
"Martyn": ["https://www.instagram.com/martyn3024", 0],
"Mary Lattimore": ["https://marylattimoreharpist.bandcamp.com/", 1],
"Matt Werth": ["https://rvng.bandcamp.com/", 0],
"Mike Midnight": ["https://www.instagram.com/mikemidnight_/?hl=en", 0],
"Mississippi Records": ["https://www.instagram.com/mississippirecords", 0],
"Moopie": ["https://soundcloud.com/moopie", 0],
"Naone": ["https://soundcloud.com/na_one", 0],
"Nashpaints": ["https://soundcloud.com/nash-paints", 1],
"Nídia": ["https://soundcloud.com/nidiasukulbembe", 0],
"Octo Octa": ["https://soundcloud.com/octoocta", 0],
"OKO DJ": ["https://soundcloud.com/okodj", 0],
"oma totem": ["https://www.instagram.com/oma.totem", 0],
"Optimo (Espacio)": ["https://optimomusic.bandcamp.com", 0],
"Pan·American": ["https://panamerican.bandcamp.com/music", 1],
"Paperclip Minimiser": ["https://paperclipminimiser.bandcamp.com/album/ii", 1],
"Paula Tape": ["https://soundcloud.com/paulatape", 0],
"Pavel Milyakov": ["https://buttechno.bandcamp.com/", 1],
"Pender Street Steppers": ["https://soundcloud.com/pender-street-steppers", 0],
"Phil Yeah": ["https://www.instagram.com/philyeah", 0],
"Pilooski": ["https://www.instagram.com/pilooski_/?hl=en", 0],
"Qoso": ["https://soundcloud.com/qoso", 0],
"QRTR": ["https://jointfunction.bandcamp.com/music", 0],
"Quiet Light": ["https://quietlight.bandcamp.com", 1],
"RHR": ["https://soundcloud.com/rhrmusiq", 0],
"Richard": ["https://www.instagram.com/nestce.pas", 1],
"Robert Aiki Aubrey Lowe": ["https://robertaikiaubreylowe.bandcamp.com/", 1],
"Roza Terenzi": ["https://soundcloud.com/roza-terenzi", 0],
"Russell Alexander": ["https://www.instagram.com/russellbalexander", 0],
"Sandwell District": ["https://soundcloud.com/sandwelldistrict", 0],
"Security Dog": ["https://www.instagram.com/03_securitydog.flac", 0],
"Sergeant": ["https://stroomtv.bandcamp.com/album/sergeant", 1],
"SEXTILE": ["https://sextile.bandcamp.com", 1],
"Shai FM": ["https://www.instagram.com/_shai.fm_/", 0],
"Shane Parish": ["https://shaneparish.bandcamp.com/album/autechre-guitar-2", 1],
"Shaun D": ["https://www.instagram.com/djshaund/", 0],
"Skee Mask": ["https://soundcloud.com/skeemask-music", 0],
"Soul Summit": ["https://soundcloud.com/soul-summit-music", 0],
"Space Drum Meditation": ["https://spacedrummeditation.bandcamp.com/album/space-drum-meditation-sdm004", 0],
"Special Guest DJ": ["https://www.instagram.com/yungsanta", 0],
"Spivak": ["https://www.instagram.com/spivakmaria/?hl=en", 1],
"Spray": ["https://soundcloud.com/sprayforever", 0],
"Stone": ["https://www.instagram.com/stone____________________/?hl=en", 1],
"The Space Lady": ["https://www.instagram.com/thespaceladymusic/?hl=en", 1],
"Theo Parrish": ["https://soundcloud.com/theoparrish", 0],
"They Are Gutting A Body Of Water": ["https://theyareguttingabodyofwater.bandcamp.com/album/lotto", 1],
"Tiga": ["https://soundcloud.com/TIGA", 0],
"Topdown Dialectic": ["https://peakoil.bandcamp.com/album/topdown-dialectic", 1],
"Tornado Wallace": ["https://www.instagram.com/tornadowallace/?hl=en", 0],
"Trickpony": ["https://stepballchain.bandcamp.com/album/pillow-talk", 1],
"Unai Trotti": ["https://soundcloud.com/unai-trotti", 0],
"Universal Cave": ["https://www.instagram.com/universalcave/?hl=en", 0],
"upsammy": ["https://soundcloud.com/upsammy", 0],
"Valentina Magaletti": ["https://www.instagram.com/valentina_magaletti/", 1],
"Verraco": ["https://soundcloud.com/verraco", 0],
"Vlada": ["https://soundcloud.com/playvlada", 0],
"Vladimir Ivkovic": ["https://soundcloud.com/vladimir", 0],
"Wata Igarashi": ["https://soundcloud.com/wata", 0],
"Westov Temple": ["https://www.instagram.com/psychicyouth", 0],
"x3butterfly": ["https://soundcloud.com/sorrellem", 0],
"Yu Su": ["https://soundcloud.com/yu_su", 0],
"Yumi": ["https://www.instagram.com/notyumiko", 0],
"Zillas on Acid": ["https://www.instagram.com/zillasonacid", 0],
}

LABELS = {
"@": "Carpark Records",
"Andrew Max FT": "The Trilogy Tapes",
"Aurora Halal": "Mutual Dreaming",
"Autumns": "Death & Leisure",
"Avalon Emerson": "AD 93",
"Batu": "Timedance",
"Beautiful Swimmers": "Future Times",
"Bicep": "Ninja Tune",
"Binh": "Time Passages",
"Carla dal Forno": "Kallista Records",
"Carrier": "Avian",
"Cashu": "Mamba Negra",
"Chee Shimizu": "Organic Music",
"Crespi Drum Syndicate": "ISLA",
"DJ Godfather": "Databass",
"DJ LAG": "Goon Club Allstars",
"DJ Masda": "Cabaret Recordings",
"DJ Python": "Incienso",
"DJ Sundae": "Idle Press",
"Dania": "Paralaxe Editions",
"Daniel Avery": "Phantasy Sound",
"Daphni": "Jiaolong",
"De Schuurman": "Nyege Nyege Tapes",
"Debit": "Modern Love",
"Dopplereffekt": "Leisure System",
"Elori Saxl & Henry Solomon": "Western Vinyl",
"Emily A. Sprague": "RVNG Intl.",
"Eris Drew": "T4T LUV NRG",
"Erol Alkan": "Phantasy Sound",
"Father Dionysios Tabakis": "Heat Crimes",
"Gabber Eleganza": "Never Sleep",
"Gavsborg": "Equiknoxx Music",
"Hervé": "Cheap Thrills",
"Identified Patient": "Pinkman",
"JASSS": "iDEAL Recordings",
"Jeff Parker": "International Anthem",
"John Talabot": "Hivern Discs",
"Joy Guidry": "Whited Sepulchre",
"Kim Gordon": "Matador",
"Konduku": "Nous'klaer Audio",
"Lena Willikens": "Cómeme",
"Loidis": "West Mineral Ltd.",
"Ma Sha": "Kindergarten Records",
"Maara": "Step Ball Chain",
"Marcel Dettmann": "MDR",
"Mark Ernestus": "Basic Channel",
"Martyn": "3024",
"Mary Lattimore": "Ghostly International",
"Matt Werth": "RVNG Intl.",
"Mississippi Records": "Mississippi Records",
"Moopie": "A Colourful Storm",
"Nídia": "Príncipe",
"OKO DJ": "BFDM",
"Octo Octa": "T4T LUV NRG",
"Optimo (Espacio)": "Optimo Music",
"Pan·American": "Kranky",
"Paula Tape": "Rhythm Section INTL",
"Pavel Milyakov": "Gost Zvuk",
"Pender Street Steppers": "Mood Hut",
"Roza Terenzi": "Step Ball Chain",
"SEXTILE": "Sacred Bones",
"Sandwell District": "Sandwell District",
"Sergeant": "STROOM",
"Shane Parish": "Palilalia",
"Shaun D": "Nyege Nyege Tapes",
"Skee Mask": "Ilian Tape",
"Soul Summit": "Soul Summit Music",
"The Space Lady": "Night School",
"Theo Parrish": "Sound Signature",
"They Are Gutting A Body Of Water": "Smoking Room",
"Tiga": "Turbo Recordings",
"Topdown Dialectic": "Peak Oil",
"Tornado Wallace": "Running Back",
"Trickpony": "Step Ball Chain",
"Unai Trotti": "Cartulis Music",
"Verraco": "TraTraTrax",
"Vladimir Ivkovic": "Offen Music",
"Wata Igarashi": "WIP",
"Yu Su": "bié Records",
"upsammy": "PAN",
}


SETTIMES = {}

COUNTRY = {"US": "United States", "GB": "United Kingdom", "DE": "Germany", "NL": "Netherlands", "FR": "France", "IT": "Italy", "JP": "Japan", "CA": "Canada", "AU": "Australia", "BE": "Belgium", "ES": "Spain", "MX": "Mexico", "CO": "Colombia", "BR": "Brazil", "CL": "Chile", "PE": "Peru", "EC": "Ecuador", "VE": "Venezuela", "DO": "Dominican Republic", "GT": "Guatemala", "BO": "Bolivia", "PR": "Puerto Rico", "JM": "Jamaica", "IE": "Ireland", "NO": "Norway", "SE": "Sweden", "DK": "Denmark", "PL": "Poland", "RU": "Russia", "UA": "Ukraine", "RO": "Romania", "RS": "Serbia", "CH": "Switzerland", "LT": "Lithuania", "PT": "Portugal", "GE": "Georgia", "TR": "Turkey", "IL": "Israel", "PS": "Palestine", "LB": "Lebanon", "IR": "Iran", "TN": "Tunisia", "ET": "Ethiopia", "KE": "Kenya", "NG": "Nigeria", "ZA": "South Africa", "KR": "South Korea", "CN": "China", "TW": "Taiwan", "NZ": "New Zealand", "IN": "India", "GR": "Greece"}
REGION = {"US": "North America", "CA": "North America", "MX": "North America", "PR": "North America", "GB": "UK & Ireland", "IE": "UK & Ireland", "DE": "Europe", "NL": "Europe", "FR": "Europe", "IT": "Europe", "BE": "Europe", "ES": "Europe", "NO": "Europe", "SE": "Europe", "DK": "Europe", "PL": "Europe", "RU": "Europe", "UA": "Europe", "RO": "Europe", "RS": "Europe", "CH": "Europe", "LT": "Europe", "PT": "Europe", "GE": "Europe", "TR": "Europe", "CO": "Latin America", "BR": "Latin America", "CL": "Latin America", "PE": "Latin America", "EC": "Latin America", "VE": "Latin America", "DO": "Latin America", "GT": "Latin America", "BO": "Latin America", "JM": "Latin America", "IL": "Middle East & Africa", "PS": "Middle East & Africa", "LB": "Middle East & Africa", "IR": "Middle East & Africa", "TN": "Middle East & Africa", "ET": "Middle East & Africa", "KE": "Middle East & Africa", "NG": "Middle East & Africa", "ZA": "Middle East & Africa", "JP": "Asia", "KR": "Asia", "CN": "Asia", "TW": "Asia", "IN": "Asia", "AU": "Oceania", "NZ": "Oceania", "GR": "Europe"}

def load_optional(p):
    if os.path.exists(p):
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    return {}

GEN = load_optional("genre_classification.json") # from fetch_genres.py (tagged genres)
BIO = load_optional("bio_classification.json")    # from classify_bios.py (prose bios)
USER = load_optional("overrides.json")            # yours; wins over everything

artists = []
for name in LINEUP:
    city, cc, grp, genres, slug = META[name]
    url, live = LINKS[name]
    label = LABELS.get(name, "")
    for SRC in (GEN, BIO):                      # tagged genres beat prose bios
        if name in SRC:
            b = SRC[name]
            if not grp and b.get("groups"): grp = b["groups"]
            if not genres: genres = list(b.get("genres", []))
            if not url: url = b.get("bc")
    if name in USER:
        u = USER[name]
        grp = u.get("groups", grp); city = u.get("city", city)
        cc = u.get("cc", cc); genres = u.get("genres", genres)
        label = u.get("label", label); url = u.get("url", url)
    artists.append({
        "name": name, "city": city,
        "country": COUNTRY.get(cc, "Unknown"), "region": REGION.get(cc, "Unknown"),
        "groups": [GROUPMAP[g] for g in grp], "genres": genres, "label": label,
        "url": url, "live": bool(live), "set": SETTIMES.get(name),
    })

data = {
    "meta": {"title": "Making Time 2026", "generated": "2026-08-15", "settimes": bool(SETTIMES),
             "source": "https://makingtimeisrad.com/lineup/"},
    "artists": artists,
}
with open("data.js", "w", encoding="utf-8") as f:
    f.write("// Making Time 2026 bill — see build_data.py for sources and pipeline\n")
    f.write("const MT_DATA = ")
    json.dump(data, f, ensure_ascii=False, indent=1)
    f.write(";\n")

print(f"{len(artists)} artists · {sum(1 for a in artists if a['label'])} labels · "
      f"{sum(1 for a in artists if a['url'] and 'bandcamp' in (a['url'] or ''))} bandcamp links · "
      f"{sum(1 for a in artists if a['live'])} live sets")
