# -*- coding: utf-8 -*-
"""Making Time 2026 official set times, transcribed from the three day posters
(Fri Sep 18 / Sat Sep 19 / Sun Sep 20, Fort Mifflin). Six zones per day.

Format: bill: (day, zone, start, end, live, [members])
b2bs split into members like the Sustain-Release tool; billed name stays the unit.
"""

TZ, MZ, FZ, O5, LR, IZ = ("Transcendental Zone", "Majestic Zone", "Futuristic Zone",
                          "Option5", "The Lot Radio Zone", "∞ Zone")

SETTIMES = {
# ---------------- FRIDAY SEP 18 ----------------
"Ivan Liechti":        ("Fri", TZ, "1:00PM", "3:30PM", False, ["Ivan Liechti"]),
"Mike Midnight":       ("Fri", TZ, "3:30PM", "5:15PM", False, ["Mike Midnight"]),
"OKO DJ":              ("Fri", TZ, "5:15PM", "7:00PM", False, ["OKO DJ"]),
"Los Thuthanaka":      ("Fri", TZ, "7:00PM", "7:45PM", True,  ["Los Thuthanaka"]),
"CCL":                 ("Fri", TZ, "7:45PM", "9:30PM", False, ["CCL"]),
"SEXTILE":             ("Fri", TZ, "9:30PM", "10:15PM", True, ["SEXTILE"]),
"Marcel Dettmann":     ("Fri", TZ, "10:15PM", "12:00AM", False, ["Marcel Dettmann"]),
"John Talabot":        ("Fri", TZ, "12:00AM", "2:00AM", False, ["John Talabot"]),

"Bianca Lexis":        ("Fri", MZ, "1:00PM", "3:30PM", False, ["Bianca Lexis"]),
"Honcho":              ("Fri", MZ, "3:30PM", "5:00PM", False, ["Honcho"]),
"Jump Source":         ("Fri", MZ, "5:00PM", "6:30PM", True,  ["Jump Source"]),
"Loidis":              ("Fri", MZ, "6:30PM", "8:00PM", False, ["Loidis"]),
"Konduku":             ("Fri", MZ, "8:00PM", "9:30PM", False, ["Konduku"]),
"DJ Masda":            ("Fri", MZ, "9:30PM", "11:15PM", False, ["DJ Masda"]),
"Dopplereffekt":       ("Fri", MZ, "11:15PM", "12:15AM", False, ["Dopplereffekt"]),
"Aurora Halal b2b Verraco": ("Fri", MZ, "12:15AM", "3:00AM", False, ["Aurora Halal", "Verraco"]),

"Richard":             ("Fri", FZ, "4:00PM", "4:45PM", True, ["Richard"]),
"@":                   ("Fri", FZ, "5:45PM", "6:15PM", True, ["@"]),
"Shane Parish — Autechre guitar": ("Fri", FZ, "7:15PM", "8:00PM", True, ["Shane Parish"]),
"upsammy & Valentina Magaletti": ("Fri", FZ, "8:45PM", "9:30PM", True, ["upsammy", "Valentina Magaletti"]),
"Sergeant":            ("Fri", FZ, "10:15PM", "11:00PM", True, ["Sergeant"]),
"Debit":               ("Fri", FZ, "11:45PM", "12:30AM", True, ["Debit"]),
"Paperclip Minimiser": ("Fri", FZ, "1:00AM", "1:45AM", True, ["Paperclip Minimiser"]),

"DJ Python b2b QOSO":  ("Fri", O5, "2:00PM", "6:00PM", False, ["DJ Python", "QOSO"]),
"Nídia":               ("Fri", O5, "6:00PM", "7:30PM", False, ["Nídia"]),
"JASSS":               ("Fri", O5, "7:30PM", "9:00PM", False, ["JASSS"]),
"DJ LAG":              ("Fri", O5, "9:00PM", "10:00PM", False, ["DJ LAG"]),
"Identified Patient":  ("Fri", O5, "10:00PM", "11:30PM", False, ["Identified Patient"]),
"mad miran":           ("Fri", O5, "11:30PM", "1:00AM", False, ["mad miran"]),
"DJ Godfather":        ("Fri", O5, "1:00AM", "2:00AM", False, ["DJ Godfather"]),

"Cubby presents Spatial Awareness": ("Fri", LR, "1:00PM", "2:30PM", False, ["Cubby"]),
"Yumi":                ("Fri", LR, "2:30PM", "4:00PM", False, ["Yumi"]),
"Gavsborg":            ("Fri", LR, "4:00PM", "5:30PM", False, ["Gavsborg"]),
"Naone":               ("Fri", LR, "5:30PM", "7:00PM", False, ["Naone"]),
"1morning":            ("Fri", LR, "7:00PM", "8:30PM", False, ["1morning"]),
"Unai Trotti":         ("Fri", LR, "8:30PM", "10:15PM", False, ["Unai Trotti"]),
"De Schuurman b2b Shaun D.": ("Fri", LR, "10:15PM", "11:45PM", False, ["De Schuurman", "Shaun D."]),
"Cry":                 ("Fri", LR, "11:45PM", "12:30AM", True, ["Cry"]),
"Bobby Beethoven":     ("Fri", LR, "12:30AM", "2:00AM", False, ["Bobby Beethoven"]),

"afro.fem":            ("Fri", IZ, "1:30PM", "3:00PM", False, ["afro.fem"]),
"Eev Frances":         ("Fri", IZ, "3:00PM", "4:15PM", False, ["Eev Frances"]),
"JJJJJerome Ellis":    ("Fri", IZ, "4:15PM", "5:00PM", True, ["JJJJJerome Ellis"]),
"LEECH":               ("Fri", IZ, "5:00PM", "6:30PM", False, ["LEECH"]),
"Jeff Zeigler":        ("Fri", IZ, "6:30PM", "7:15PM", True, ["Jeff Zeigler"]),
"Chee Shimizu":        ("Fri", IZ, "7:15PM", "9:15PM", False, ["Chee Shimizu"]),
"Elori Saxl & Henry Solomon": ("Fri", IZ, "9:15PM", "10:00PM", True, ["Elori Saxl", "Henry Solomon"]),
"Russell Alexander":   ("Fri", IZ, "10:00PM", "11:30PM", False, ["Russell Alexander"]),
"Kiernan Laveaux":     ("Fri", IZ, "11:30PM", "1:00AM", False, ["Kiernan Laveaux"]),
"DJ Papaya":           ("Fri", IZ, "1:00AM", "2:00AM", False, ["DJ Papaya"]),

# ---------------- SATURDAY SEP 19 ----------------
"Luke Mele":           ("Sat", TZ, "1:00PM", "3:00PM", False, ["Luke Mele"]),
"DJ Sundae":           ("Sat", TZ, "3:00PM", "5:00PM", False, ["DJ Sundae"]),
"Carla dal Forno":     ("Sat", TZ, "5:00PM", "5:45PM", True, ["Carla dal Forno"]),
"Yu Su b2b Moopie":    ("Sat", TZ, "5:45PM", "7:45PM", False, ["Yu Su", "Moopie"]),
"Avalon Emerson":      ("Sat", TZ, "7:45PM", "9:45PM", False, ["Avalon Emerson"]),
"Kim Gordon":          ("Sat", TZ, "9:45PM", "10:30PM", True, ["Kim Gordon"]),
"Binh":                ("Sat", TZ, "10:30PM", "12:15AM", False, ["Binh"]),
"Bicep":               ("Sat", TZ, "12:15AM", "2:00AM", False, ["Bicep"]),

"Universal Cave":      ("Sat", MZ, "1:00PM", "2:30PM", False, ["Universal Cave"]),
"Kiernan Laveaux (Majestic)": ("Sat", MZ, "2:30PM", "4:00PM", False, ["Kiernan Laveaux"]),
"Trickpony":           ("Sat", MZ, "4:00PM", "4:45PM", True, ["Trickpony"]),
"Gavsborg b2b Arthur": ("Sat", MZ, "4:45PM", "6:30PM", False, ["Gavsborg", "Arthur"]),
"Mark Ernestus":       ("Sat", MZ, "6:30PM", "8:00PM", False, ["Mark Ernestus"]),
"They Are Gutting a Body of Water": ("Sat", MZ, "8:00PM", "8:45PM", True, ["They Are Gutting a Body of Water"]),
"Optimo (Espacio)":    ("Sat", MZ, "8:45PM", "10:30PM", False, ["Optimo (Espacio)"]),
"Sandwell District":   ("Sat", MZ, "10:30PM", "12:15AM", False, ["Sandwell District"]),
"Batu":                ("Sat", MZ, "12:15AM", "2:00AM", False, ["Batu"]),
"Laraaji":             ("Sat", MZ, "2:00AM", "3:00AM", True, ["Laraaji"]),

"Ciro Vitiello":       ("Sat", FZ, "4:15PM", "5:00PM", True, ["Ciro Vitiello"]),
"Cancer House":        ("Sat", FZ, "5:45PM", "6:15PM", True, ["Cancer House"]),
"Dagmar Zuniga":       ("Sat", FZ, "7:15PM", "8:00PM", True, ["Dagmar Zuniga"]),
"Dania":               ("Sat", FZ, "8:45PM", "9:30PM", True, ["Dania"]),
"Crespi Drum Syndicate": ("Sat", FZ, "10:15PM", "11:00PM", True, ["Crespi Drum Syndicate"]),
"Carrier":             ("Sat", FZ, "11:45PM", "12:30AM", True, ["Carrier"]),
"Autumns":             ("Sat", FZ, "1:00AM", "1:45AM", True, ["Autumns"]),

"Willikens & Ivkovic": ("Sat", O5, "2:00PM", "6:00PM", False, ["Lena Willikens", "Vladimir Ivkovic"]),
"Vlada":               ("Sat", O5, "6:00PM", "7:30PM", False, ["Vlada"]),
"Maara":               ("Sat", O5, "7:30PM", "9:00PM", False, ["Maara"]),
"DJ MARIA.":           ("Sat", O5, "9:00PM", "10:30PM", False, ["DJ MARIA."]),
"Wata Igarashi":       ("Sat", O5, "10:30PM", "12:00AM", False, ["Wata Igarashi"]),
"Cashu b2b RHR":       ("Sat", O5, "12:00AM", "2:00AM", False, ["Cashu", "RHR"]),

"Moopie (Lot)":        ("Sat", LR, "1:00PM", "2:00PM", False, ["Moopie"]),
"Soul Summit":         ("Sat", LR, "2:00PM", "3:30PM", False, ["Soul Summit"]),
"Hervé":               ("Sat", LR, "3:30PM", "5:00PM", False, ["Hervé"]),
"BASHKKA":             ("Sat", LR, "5:45PM", "7:15PM", False, ["BASHKKA"]),
"Roza Terenzi":        ("Sat", LR, "7:15PM", "8:45PM", False, ["Roza Terenzi"]),
"Ehua":                ("Sat", LR, "8:45PM", "10:15PM", False, ["Ehua"]),
"Carlos Souffront":    ("Sat", LR, "10:15PM", "12:00AM", False, ["Carlos Souffront"]),
"EAR":                 ("Sat", LR, "12:00AM", "12:30AM", True, ["EAR"]),
"Ma Sha":              ("Sat", LR, "12:30AM", "2:00AM", False, ["Ma Sha"]),

"Phil Yeah":           ("Sat", IZ, "1:00PM", "2:45PM", False, ["Phil Yeah"]),
"CCL presents Liquidtime": ("Sat", IZ, "2:45PM", "4:15PM", False, ["CCL"]),
"Pan•American":        ("Sat", IZ, "4:15PM", "5:00PM", True, ["Pan•American"]),
"x3butterfly (ambient set)": ("Sat", IZ, "5:00PM", "6:30PM", False, ["x3butterfly"]),
"Emily A. Sprague":    ("Sat", IZ, "6:30PM", "7:15PM", True, ["Emily A. Sprague"]),
"Martyn — Music For Existing": ("Sat", IZ, "7:15PM", "8:45PM", False, ["Martyn"]),
"Joy Guidry":          ("Sat", IZ, "8:45PM", "9:30PM", True, ["Joy Guidry"]),
"Mississippi Records": ("Sat", IZ, "9:30PM", "10:30PM", False, ["Mississippi Records"]),
"Matt Werth (RVNG INTL)": ("Sat", IZ, "10:30PM", "12:00AM", False, ["Matt Werth"]),
"Universal Cave (∞)":  ("Sat", IZ, "12:00AM", "2:00AM", False, ["Universal Cave"]),

# ---------------- SUNDAY SEP 20 ----------------
"Carla dal Forno (DJ set)": ("Sun", TZ, "1:00PM", "2:00PM", False, ["Carla dal Forno"]),
"Jeff Parker & Mary Lattimore": ("Sun", TZ, "2:00PM", "3:00PM", True, ["Jeff Parker", "Mary Lattimore"]),
"Pender Street Steppers": ("Sun", TZ, "3:00PM", "4:30PM", False, ["Pender Street Steppers"]),
"Atlas Sound":         ("Sun", TZ, "4:30PM", "5:15PM", True, ["Atlas Sound"]),
"Theo Parrish":        ("Sun", TZ, "5:15PM", "8:15PM", False, ["Theo Parrish"]),
"Octo Octa b2b Eris Drew": ("Sun", TZ, "8:15PM", "10:15PM", False, ["Octo Octa", "Eris Drew"]),
"Daphni":              ("Sun", TZ, "10:15PM", "12:00AM", False, ["Daphni"]),

"Mario Cotto":         ("Sun", MZ, "1:00PM", "2:00PM", False, ["Mario Cotto"]),
"Pilooski":            ("Sun", MZ, "2:00PM", "3:30PM", False, ["Pilooski"]),
"Avalon Emerson & The Charm": ("Sun", MZ, "3:30PM", "4:15PM", True, ["Avalon Emerson"]),
"Paula Tape":          ("Sun", MZ, "4:15PM", "5:45PM", False, ["Paula Tape"]),
"John Talabot (transcendisco set)": ("Sun", MZ, "5:45PM", "7:15PM", False, ["John Talabot"]),
"Daniel Avery":        ("Sun", MZ, "7:15PM", "8:15PM", True, ["Daniel Avery"]),
"Erol Alkan":          ("Sun", MZ, "8:15PM", "10:00PM", False, ["Erol Alkan"]),
"Skee Mask":           ("Sun", MZ, "10:00PM", "12:00AM", False, ["Skee Mask"]),

"Pavel Milyakov & Alex Zhang Hungtai": ("Sun", FZ, "5:30PM", "6:15PM", True, ["Pavel Milyakov", "Alex Zhang Hungtai"]),
"Nashpaints":          ("Sun", FZ, "7:00PM", "7:45PM", True, ["Nashpaints"]),
"The Space Lady":      ("Sun", FZ, "8:30PM", "9:15PM", True, ["The Space Lady"]),
"Topdown Dialectic":   ("Sun", FZ, "10:00PM", "10:45PM", True, ["Topdown Dialectic"]),

"Tornado Wallace":     ("Sun", O5, "1:00PM", "5:30PM", False, ["Tornado Wallace"]),
"Main Phase":          ("Sun", O5, "5:30PM", "7:00PM", False, ["Main Phase"]),
"Introspekt":          ("Sun", O5, "7:00PM", "8:30PM", False, ["Introspekt"]),
"Space Drum Meditation": ("Sun", O5, "8:30PM", "10:00PM", False, ["Space Drum Meditation"]),
"Lena Willikens b2b upsammy": ("Sun", O5, "10:00PM", "12:00AM", False, ["Lena Willikens", "upsammy"]),

"Ian Kim Judd":        ("Sun", LR, "1:00PM", "3:00PM", False, ["Ian Kim Judd"]),
"Beautiful Swimmers":  ("Sun", LR, "3:00PM", "4:30PM", False, ["Beautiful Swimmers"]),
"Andrew Max ft All 7s": ("Sun", LR, "5:15PM", "6:00PM", False, ["Andrew Max"]),
"Deep Creep":          ("Sun", LR, "6:00PM", "7:30PM", False, ["Deep Creep"]),
"Baalti":              ("Sun", LR, "7:30PM", "9:00PM", False, ["Baalti"]),
"DJ SWISHA b2b Jewelssea": ("Sun", LR, "9:00PM", "10:30PM", False, ["DJ SWISHA", "Jewelssea"]),
"Tiga":                ("Sun", LR, "10:30PM", "12:00AM", False, ["Tiga"]),

"Security Dog":        ("Sun", IZ, "1:30PM", "3:00PM", False, ["Security Dog"]),
"Gravers Lane":        ("Sun", IZ, "3:00PM", "4:00PM", False, ["Gravers Lane"]),
"Loradeniz":           ("Sun", IZ, "4:00PM", "4:45PM", True, ["Loradeniz"]),
"Robert Aiki Aubrey Lowe": ("Sun", IZ, "4:45PM", "5:30PM", True, ["Robert Aiki Aubrey Lowe"]),
"Colombian Drone Mafia": ("Sun", IZ, "5:30PM", "7:00PM", False, ["Colombian Drone Mafia"]),
"Stone":               ("Sun", IZ, "7:00PM", "7:45PM", True, ["Stone"]),
"Special Guest DJ":    ("Sun", IZ, "7:45PM", "9:15PM", False, ["Special Guest DJ"]),
"Westov Temple":       ("Sun", IZ, "9:15PM", "10:45PM", False, ["Westov Temple"]),
}
